CREATE DATABASE porque;

USE porque;

-- TABLA ATENCION
CREATE TABLE T_ATENCION (
  IN_CODIGO_ATE INT(11) NOT NULL AUTO_INCREMENT,
  VC_NHISTORIA_ATE VARCHAR(20) DEFAULT NULL COMMENT 'Numero de Historia Clinica',
  VC_CODIGOSIS_ATE VARCHAR (45) DEFAULT NULL COMMENT 'Codigo de SIS',
  VC_NOMBRES_ATE VARCHAR (200) DEFAULT NULL COMMENT 'Nombres Paciente',
  IN_EDAD_ATE INT (11) DEFAULT NULL COMMENT 'Edad Paciente',
  VC_TIPUSAURIO_ATE VARCHAR (50) DEFAULT NULL COMMENT 'Tipo de Usuario',
  VC_TIPATENCION_ATE VARCHAR (45) DEFAULT NULL COMMENT 'Tipo de Atencion',
  VC_ESPECIALIDAD_ATE VARCHAR (100) DEFAULT NULL COMMENT 'Especilidad de Atencion',
  VC_OTROS_ATE VARCHAR (100) DEFAULT NULL COMMENT 'Otros valores',
  DT_FREGISTRO_ATE DATETIME DEFAULT NULL COMMENT 'Fecha de Registro',
  INT_CODIGO_HIC INT (11) DEFAULT NULL COMMENT 'Codigo Historia Clinica',
  IN_CODIGO_PSA INT (11) DEFAULT NULL COMMENT 'Codigo Personal de Salud',
  IN_CODIGO_PAC INT (11) DEFAULT NULL COMMENT 'Codigo Paciente',
  PRIMARY KEY (IN_CODIGO_ATE),
  KEY `fk_atencion_doctor_idx` (IN_CODIGO_PSA),
  KEY `fk_atencion_paciente_idx` (IN_CODIGO_PAC),
  CONSTRAINT `fk_atencion_doctor` FOREIGN KEY (IN_CODIGO_PSA) REFERENCES T_PERSONAL_SALUD (IN_CODIGO_PSA) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_atencion_paciente` FOREIGN KEY (IN_CODIGO_PAC) REFERENCES T_PACIENTE (IN_CODIGO_PAC) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'Tabla Atencion Paciente';

-- TABLA HISTORIA CLINICA
CREATE TABLE T_HISTORIA_CLINICA (
  IN_CODIGO_HIC INT (11) NOT NULL AUTO_INCREMENT,
  VC_NHISTORI_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Numero de Historia Clinica',
  IN_CODIGO_PAC INT (11) DEFAULT NULL COMMENT 'Codigo Paciente',
  VA_FCONSULTA_HIC VARCHAR (30) DEFAULT NULL COMMENT 'Fecha de Consulta',
  VC_HCONSULTA_HIC VARCHAR (30) DEFAULT NULL COMMENT 'Hora de Consulta',
  IN_EDAD_HIC INT (11) DEFAULT NULL COMMENT 'Edad de Paciente',
  VC_MOTIVO_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Motivo de Atencion Paciente',
  VC_SIGNOS_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Signos Paciente',
  VC_RELATO_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Relato Paciente',
  VC_VACUNAS_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Vacunas Paciente',
  VC_APETITO_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Apetito Paciente',
  VC_SED_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Sed Paciente',
  VC_SUENIO_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Sueño Paciente',
  VC_ORINA_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Orina Paciente',
  VC_DEPOSICION_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Deposicion Paciente',
  CH_FIEBRE_HIC CHAR (2) DEFAULT NULL COMMENT 'Fiebre Paciente',
  CH_VIAJE_HIC CHAR (2) DEFAULT NULL COMMENT 'Viaje Paciente',
  VC_LUGAR_HIC VARCHAR (150) DEFAULT NULL COMMENT 'Lugar Viaje Paciente',
  CH_TOS_HIC CHAR (2) DEFAULT NULL COMMENT 'Tos Paciente',
  CH_SECRESION_HIC CHAR (2) DEFAULT NULL COMMENT 'Secresion Paciente',
  VC_FUR_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Fur Paciente',
  VC_EXAFISICO_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Examen Fisico Paciente',
  VC_TEMP_HIC VARCHAR (20) DEFAULT NULL COMMENT 'Temperatura Paciente',
  VC_PA_HIC VARCHAR (20) DEFAULT NULL COMMENT 'PA Paciente',
  VC_FC_HIC VARCHAR (20) DEFAULT NULL COMMENT 'FC Paciente',
  VC_FR_HIC VARCHAR (20) DEFAULT NULL COMMENT 'FR Paciente',
  VC_PESO_HIC VARCHAR (20) DEFAULT NULL COMMENT 'Peso Paciente',
  VC_TALLA_HIC VARCHAR (20) DEFAULT NULL COMMENT 'Talla Paciente',
  VC_PABD_HIC VARCHAR (20) DEFAULT NULL COMMENT 'PABD Paciente',
  VC_SATURACION_HIC VARCHAR (30) DEFAULT NULL COMMENT 'Saturacion Paciente',
  VC_DIAGNOSTICO_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Diagnostico Paciente',
  VC_TIPEXAMEN_HIC VARCHAR (45) DEFAULT NULL COMMENT 'Tipo Examen Paciente',
  VC_CIEX_HIC VARCHAR (50) DEFAULT NULL COMMENT 'CIEX Paciente',
  VC_TRATAMIENTO_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Tratamiento Paciente',
  VC_VIA_HIC VARCHAR (50) DEFAULT NULL COMMENT 'VIA Paciente',
  VC_DOSIS_HIC VARCHAR (50) DEFAULT NULL COMMENT 'Dosis Paciente',
  VC_FRECUENCIA_HIC VARCHAR (50) DEFAULT NULL COMMENT 'Frecuencia Paciente',
  VC_MEDHIG_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Medidas Higienicas Paciente',
  VC_EXAUX_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Examenes Auxiliares Paciente',
  VC_MEDPREV_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Medidas Preventivas Paciente',
  VC_PROCONSULTA_HIC VARCHAR (30) DEFAULT NULL COMMENT 'Proxima Consulta Paciente',
  VC_OBSERVACIONES_HIC VARCHAR (255) DEFAULT NULL COMMENT 'Observaciones Paciente',
  DT_FREGISTRO_HIC DATETIME DEFAULT NULL COMMENT 'Fecha de Registro Historia Clinica',
  IN_CONDIGO_CON INT (11) DEFAULT NULL COMMENT 'Codigo Consultorio',
  DT_FCAMBIO_HIC DATETIME DEFAULT NULL COMMENT 'Fecha de Cambio Historia Clinica',
  IN_CODIGO_PSA INT (11) DEFAULT NULL COMMENT 'Codigo Personal de Salud',
  IN_CODIGO_ATE INT (11) DEFAULT NULL COMMENT 'Codigo Atencion',
  PRIMARY KEY (IN_CODIGO_HIC),
  KEY `fk_historiaclinica_paciente_idx` (`idpaciente`),
  KEY `fk_historiaclinica_consultorio_idx` (`idconsultorio`),
  KEY `fk_historiaclinica_doctor_idx` (`iddoctor`),
  KEY `fk_historiaclinica_atencion_idx` (`idatencion`),
  CONSTRAINT `fk_historiaclinica_atencion` FOREIGN KEY (`idatencion`) REFERENCES `atencion` (`idatencion`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_historiaclinica_consultorio` FOREIGN KEY (`idconsultorio`) REFERENCES `consultorio` (`idconsultorio`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_historiaclinica_doctor` FOREIGN KEY (`iddoctor`) REFERENCES `doctor` (`iddoc`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_historiaclinica_paciente` FOREIGN KEY (`idpaciente`) REFERENCES `paciente` (`idpac`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'Tabla Historia Clinica';

-- TABLA PERSONAL DE SALUD
CREATE TABLE T_PERSONAL_SALUD (
  IN_CODIGO_PSA INT (11) NOT NULL AUTO_INCREMENT,
  VC_DNI_PSA VARCHAR (11) NOT NULL,
  VC_NOMBRE_PSA VARCHAR (80) NOT NULL,
  VC_APELLIDO_PSA VARCHAR (150) NOT NULL,
  VC_EMAIL_PSA VARCHAR (150) NOT NULL,
  VA_FNACIMIENTO_PSA VARCHAR (20) NOT NULL COMMENT 'Fecha de Nacimiento Personal de Salud',
  VC_GENERO_PSA VARCHAR (12) NOT NULL,
  VC_DIRECCION_PSA VARCHAR (200) DEFAULT NULL,
  VC_DEPARTAMENTO_PSA VARCHAR (20) DEFAULT NULL,
  VC_PROVINCIA_PSA VARCHAR (30) DEFAULT NULL,
  VC_DISTRITO_PSA VARCHAR (30) DEFAULT NULL,
  VC_PROFESION_PSA VARCHAR (100) NOT NULL COMMENT 'Profesion Personal de Salud',
  VC_COLEGIATURA_PSA VARCHAR (20) DEFAULT NULL COMMENT 'Numero Colegiatura Personal de Salud',
  VC_TELEFONO_PSA VARCHAR (40) NOT NULL,
  VC_AVATAR_PSA VARCHAR (200) NOT NULL COMMENT 'Foto Persil Personal de Salud',
  VC_BIOGRAFIA_PSA TEXT NOT NULL,
  DT_FREGISTRO_PSA DATETIME DEFAULT NULL COMMENT 'Fecha de Registro Personal de Salud',
  TI_ESTADO_PSA TINYINT (1) DEFAULT NULL COMMENT '1 Activo, 0 Inactivo',
  IN_OCULTO_PSA INT (11) DEFAULT 0,
  VC_FIRMA_PSA VARCHAR (200) DEFAULT NULL,
  PRIMARY KEY (IN_CODIGO_PSA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'Tabla Personal de Salud';

-- TABLA EDUCACION PERSONAL DE SALUD
CREATE TABLE T_EDUCACION_PSA (
  IN_CODIGO_EDU INT (11) NOT NULL AUTO_INCREMENT,
  IN_CODIGO_PSA INT (11) NOT NULL COMMENT 'Codigo Personal de Salud',
  VC_CENTRO_EDU VARCHAR (255) NOT NULL COMMENT 'Centro de Estudio',
  VC_ESPECIALIDAD_EDU VARCHAR (255) NOT NULL COMMENT 'Especialidad de Estudio',
  VC_PERIODO_EDU VARCHAR (45) NOT NULL COMMENT 'Periodo de Estudios',
  PRIMARY KEY (IN_CODIGO_EDU),
  KEY `fk_educacion_doctor_idx` (IN_CODIGO_PSA),
  CONSTRAINT `fk_educacion_doctor` FOREIGN KEY (`iddoc`) REFERENCES `doctor` (`iddoc`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- TABLA EXPERIENCIA PERSONAL DE SALUD
CREATE TABLE T_EXPERIENCIA_PSA (
  IN_CODIGO_EXP INT (11) NOT NULL AUTO_INCREMENT,
  IN_CODIGO_PSA INT (11) NOT NULL COMMENT 'Codigo Personal de Salud',
  VC_EMPRESA_EXP VARCHAR (200) NOT NULL COMMENT 'Empresa de Trabajo',
  VC_CARGO_EXP VARCHAR (255) NOT NULL COMMENT 'Cargo de Trabajo',
  VC_FINICIO_EXP VARCHAR (100) DEFAULT NULL COMMENT 'Fecha Inicio Trabajo',
  VC_FFIN_EXP VARCHAR (100) DEFAULT NULL COMMENT  'Fecha Fin Trabajo',
  IN_TANIO_EXP INT (11) DEFAULT NULL COMMENT 'Cantidad de Años',
  IN_TMES_EXP INT (11) DEFAULT NULL COMMENT 'Cantidad de Meses',
  PRIMARY KEY (IN_CODIGO_EXP),
  KEY `fk_experiencia_doctor_idx` (`iddoc`),
  CONSTRAINT `fk_experiencia_doctor` FOREIGN KEY (`iddoc`) REFERENCES `doctor` (`iddoc`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- TABLA PACIENTE
CREATE TABLE T_PACIENTE (
  IN_CODIGO_PAC INT (11) NOT NULL AUTO_INCREMENT COMMENT 'ID Paciente',
  VC_DNI_PAC VARCHAR (11) NOT NULL,
  VC_NOMBRE_PAC VARCHAR (80) NOT NULL,
  VC_APELLIDOS_PAC VARCHAR (150) NOT NULL,
  VC_EMAIL_PAC VARCHAR (150) NOT NULL,
  VC_FNACIMIENTO_PAC VARCHAR (10) NOT NULL COMMENT 'Fecha Nacimiento Paciente',
  VC_GENERO_PAC VARCHAR (12) NOT NULL COMMENT 'Genero Paciente',
  VC_DIRECCION_PAC VARCHAR (200) DEFAULT NULL COMMENT 'Direccion Domiclio Paciente',
  VC_DISTRITO_PAC VARCHAR (40) DEFAULT NULL,
  VC_PROVINCIA_PAC VARCHAR (30) DEFAULT NULL,
  VC_LOCALIDAD_PAC VARCHAR (30) DEFAULT NULL,
  VC_TELEFONO_PAC VARCHAR (40) DEFAULT NULL,
  VC_AVATAR_PAC VARCHAR (200) DEFAULT NULL COMMENT 'Foto Perfil Paciente',
  DT_FREGISTRO_PAC DATETIME DEFAULT NULL COMMENT 'Fecha de Registro Paciente',
  TI_ESTADO_PAC TINYINT (1) DEFAULT NULL,
  PRIMARY KEY (IN_CODIGO_PAC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'Tabla Paciente';

-- TABLA EMPLEADO
CREATE TABLE T_EMPLEADO (
  IN_CODIGO_EMP INT (11) NOT NULL AUTO_INCREMENT,
  VC_NOMBRE_EMP VARCHAR (60) NOT NULL,
  VC_APELLIDOS_EMP VARCHAR (120) NOT NULL,
  VC_EMAIL_EMP VARCHAR (150) DEFAULT NULL,
  `fecIngreso` date DEFAULT NULL,
  `telefono` varchar(20) DEFAULT NULL,
  `idpapel` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `feccreate` datetime DEFAULT NULL,
  PRIMARY KEY (`idempleado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- TABLA LOGIN
CREATE TABLE T_LOGIN (
  IN_CODIGO_LOG INT (11) NOT NULL AUTO_INCREMENT,
  VC_USUARIO_LOG VARCHAR (20) NOT NULL,
  VC_CLAVE_LOG VARCHAR (32) NOT NULL,
  IN_CODIGO_PSA INT (11) NOT NULL,
  IN_NIVEL_LOGI INT (11) NOT NULL DEFAULT 2 COMMENT '1 Admin, 2 Personal Salud, 3 Empleado',
  TI_ESTADO_LOG TINYINT (2) NOT NULL DEFAULT 1,
  IN_ADM_LOG INT (11) DEFAULT 0,
  PRIMARY KEY (IN_CODIGO_LOG)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT 'Tabla Login';
