-- CREACION DE BASE DE DATOS
CREATE DATABASE db_qumara;
CREATE DATABASE db_historial;

-- CREACION DE USUARIO
CREATE USER 'usr_qumara'@'localhost' IDENTIFIED BY 'pass_qumara';

-- CREACION DE PERMISOS A USUARIO
GRANT ALL PRIVILEGES ON db_qumara.* TO 'usr_qumara'@'localhost';

-- ACTUALIZACION DE PERMISOS
FLUSH PRIVILEGES;

-- SELECCION DE BASE DE DATOS
USE db_qumara;

SHOW DATABASEs;